#!/usr/bin/env python3
"""Shared tool catalog for Package Vulnerability Audit Skill."""
from __future__ import annotations

CATALOG = {
    "rg": {
        "binary": "rg",
        "mem_limit_mb": 512,
        "network_required": False,
        "allowed_cidrs": [],
        "level": "recommended",
        "profiles": ["minimal", "standard", "full", "binutils"],
        "required_for": ["basic-search", "dangerous-api-search"],
        "impact": "High-speed source search and dangerous API grep will use slower grep/find fallbacks or be unavailable.",
        "install_hint_id": "rg",
        "version_args": ["--version"],
        "dnf_package": "ripgrep",
    },
    "semgrep": {
        "binary": "semgrep",
        "mem_limit_mb": 2048,
        "network_required": False,
        "allowed_cidrs": [],
        "level": "recommended",
        "profiles": ["standard", "full", "binutils"],
        "required_for": ["rule-scanning", "sast-candidates"],
        "impact": "Semgrep rule-based SAST candidates will not be generated.",
        "install_hint_id": "semgrep",
        "version_args": ["--version"],
        "dnf_package": "semgrep",
    },
    "cppcheck": {
        "binary": "cppcheck",
        "mem_limit_mb": 2048,
        "network_required": False,
        "allowed_cidrs": [],
        "level": "recommended",
        "profiles": ["standard", "full", "binutils"],
        "required_for": ["c-cpp-baseline", "static-analysis"],
        "impact": "C/C++ baseline static-analysis candidates will be reduced.",
        "install_hint_id": "cppcheck",
        "version_args": ["--version"],
        "dnf_package": "cppcheck",
    },
    "osv-scanner": {
        "binary": "osv-scanner",
        "mem_limit_mb": 1024,
        "network_required": True,
        "allowed_cidrs": [],
        "level": "recommended",
        "profiles": ["standard", "full", "binutils"],
        "required_for": ["known-vulnerability-scan", "dependency-cve-scan"],
        "impact": "Known dependency vulnerability matching against OSV will not run.",
        "install_hint_id": "osv-scanner",
        "version_args": ["--version"],
    },
    "npm": {
        "binary": "npm",
        "mem_limit_mb": 1024,
        "network_required": True,
        "allowed_cidrs": [],
        "level": "optional",
        "profiles": ["standard", "full"],
        "required_for": ["node-dependency-audit", "npm-audit"],
        "impact": "Node.js projects cannot use npm audit as a dependency vulnerability fallback.",
        "install_hint_id": "npm",
        "version_args": ["--version"],
    },
    "codeql": {
        "binary": "codeql",
        "mem_limit_mb": 4096,
        "network_required": False,
        "allowed_cidrs": [],
        "level": "optional",
        "profiles": ["full", "binutils"],
        "required_for": ["semantic-analysis", "dataflow-analysis"],
        "impact": "CodeQL semantic/dataflow analysis will not run.",
        "install_hint_id": "codeql",
        "version_args": ["version"],
    },
    "joern": {
        "binary": "joern",
        "mem_limit_mb": 4096,
        "network_required": False,
        "allowed_cidrs": [],
        "level": "optional",
        "profiles": ["full"],
        "required_for": ["cpg-analysis", "deep-c-cpp-analysis"],
        "impact": "Code Property Graph analysis will not run.",
        "install_hint_id": "joern",
        "version_args": ["--version"],
    },
    "syft": {
        "binary": "syft",
        "mem_limit_mb": 1024,
        "network_required": False,
        "allowed_cidrs": [],
        "level": "optional",
        "profiles": ["full"],
        "required_for": ["sbom-generation"],
        "impact": "SBOM generation will not run.",
        "install_hint_id": "syft",
        "version_args": ["version"],
    },
    "grype": {
        "binary": "grype",
        "mem_limit_mb": 2048,
        "network_required": False,
        "allowed_cidrs": [],
        "level": "optional",
        "profiles": ["full"],
        "required_for": ["sbom-vulnerability-scan"],
        "impact": "Grype vulnerability scanning will not run.",
        "install_hint_id": "grype",
        "version_args": ["version"],
    },
    "trivy": {
        "binary": "trivy",
        "mem_limit_mb": 2048,
        "network_required": False,
        "allowed_cidrs": [],
        "level": "optional",
        "profiles": ["full"],
        "required_for": ["vulnerability-scan", "sbom-scan", "config-scan"],
        "impact": "Trivy vulnerability/SBOM/config scanning will not run.",
        "install_hint_id": "trivy",
        "version_args": ["--version"],
    },
    "afl-fuzz": {
        "binary": "afl-fuzz",
        "mem_limit_mb": 4096,
        "network_required": False,
        "allowed_cidrs": [],
        "level": "optional",
        "profiles": ["full", "binutils"],
        "required_for": ["fuzzing"],
        "impact": "AFL++ fuzzing workflows will not run.",
        "install_hint_id": "afl-fuzz",
        "version_args": ["-V"],
    },
    "gcc": {
        "binary": "gcc",
        "mem_limit_mb": 2048,
        "network_required": False,
        "allowed_cidrs": [],
        "level": "recommended",
        "profiles": ["binutils"],
        "required_for": ["asan-ubsan-build", "c-cpp-build"],
        "impact": "Binutils sanitizer builds may not run with GCC.",
        "install_hint_id": "gcc",
        "version_args": ["--version"],
        "dnf_package": "gcc",
    },
    "g++": {
        "binary": "g++",
        "mem_limit_mb": 2048,
        "network_required": False,
        "allowed_cidrs": [],
        "level": "recommended",
        "profiles": ["binutils"],
        "required_for": ["asan-ubsan-build", "c-cpp-build"],
        "impact": "Binutils sanitizer builds may not run with the C++ compiler.",
        "install_hint_id": "g++",
        "version_args": ["--version"],
        "dnf_package": "gcc-c++",
    },
    "clang": {
        "binary": "clang",
        "mem_limit_mb": 2048,
        "network_required": False,
        "allowed_cidrs": [],
        "level": "recommended",
        "profiles": ["binutils"],
        "required_for": ["asan-ubsan-build", "c-cpp-validation"],
        "impact": "Clang sanitizer validation builds cannot run.",
        "install_hint_id": "clang",
        "version_args": ["--version"],
        "dnf_package": "clang",
    },
    "clang++": {
        "binary": "clang++",
        "mem_limit_mb": 2048,
        "network_required": False,
        "allowed_cidrs": [],
        "level": "recommended",
        "profiles": ["binutils"],
        "required_for": ["asan-ubsan-build", "c-cpp-validation"],
        "impact": "C++ sanitizer validation builds cannot run with Clang.",
        "install_hint_id": "clang++",
        "version_args": ["--version"],
        "dnf_package": "clang",
    },
    "llvm-symbolizer": {
        "binary": "llvm-symbolizer",
        "mem_limit_mb": 512,
        "network_required": False,
        "allowed_cidrs": [],
        "level": "recommended",
        "profiles": ["binutils"],
        "required_for": ["asan-symbolization", "validation-diagnostics"],
        "impact": "Sanitizer traces may be unsymbolized or unusable for validation evidence.",
        "install_hint_id": "llvm-symbolizer",
        "version_args": ["--version"],
        "dnf_package": "llvm",
    },
    "llvm-profdata": {
        "binary": "llvm-profdata",
        "mem_limit_mb": 512,
        "network_required": False,
        "allowed_cidrs": [],
        "level": "optional",
        "profiles": ["binutils"],
        "required_for": ["coverage-profile-merge"],
        "impact": "LLVM coverage profile merging will not run.",
        "install_hint_id": "llvm-profdata",
        "version_args": ["--version"],
        "dnf_package": "llvm",
    },
    "llvm-cov": {
        "binary": "llvm-cov",
        "mem_limit_mb": 512,
        "network_required": False,
        "allowed_cidrs": [],
        "level": "optional",
        "profiles": ["binutils"],
        "required_for": ["coverage-reporting"],
        "impact": "LLVM coverage reporting will not run.",
        "install_hint_id": "llvm-cov",
        "version_args": ["--version"],
        "dnf_package": "llvm",
    },
    "make": {
        "binary": "make",
        "mem_limit_mb": 2048,
        "network_required": False,
        "allowed_cidrs": [],
        "level": "recommended",
        "profiles": ["binutils"],
        "required_for": ["project-build"],
        "impact": "Autotools/Make based package builds may not run.",
        "install_hint_id": "make",
        "version_args": ["--version"],
        "dnf_package": "make",
    },
    "autoconf": {
        "binary": "autoconf",
        "mem_limit_mb": 512,
        "network_required": False,
        "allowed_cidrs": [],
        "level": "recommended",
        "profiles": ["binutils"],
        "required_for": ["autotools-build"],
        "impact": "Autotools projects may not regenerate configure scripts.",
        "install_hint_id": "autoconf",
        "version_args": ["--version"],
        "dnf_package": "autoconf",
    },
    "automake": {
        "binary": "automake",
        "mem_limit_mb": 512,
        "network_required": False,
        "allowed_cidrs": [],
        "level": "recommended",
        "profiles": ["binutils"],
        "required_for": ["autotools-build"],
        "impact": "Automake based projects may not build from source.",
        "install_hint_id": "automake",
        "version_args": ["--version"],
        "dnf_package": "automake",
    },
    "libtool": {
        "binary": "libtool",
        "mem_limit_mb": 512,
        "network_required": False,
        "allowed_cidrs": [],
        "level": "recommended",
        "profiles": ["binutils"],
        "required_for": ["autotools-build"],
        "impact": "Libtool based configure/build steps may fail.",
        "install_hint_id": "libtool",
        "version_args": ["--version"],
        "dnf_package": "libtool",
    },
    "bison": {
        "binary": "bison",
        "mem_limit_mb": 512,
        "network_required": False,
        "allowed_cidrs": [],
        "level": "recommended",
        "profiles": ["binutils"],
        "required_for": ["parser-generator-build"],
        "impact": "Parser generator rebuilds may fail.",
        "install_hint_id": "bison",
        "version_args": ["--version"],
        "dnf_package": "bison",
    },
    "flex": {
        "binary": "flex",
        "mem_limit_mb": 512,
        "network_required": False,
        "allowed_cidrs": [],
        "level": "recommended",
        "profiles": ["binutils"],
        "required_for": ["lexer-generator-build"],
        "impact": "Lexer generator rebuilds may fail.",
        "install_hint_id": "flex",
        "version_args": ["--version"],
        "dnf_package": "flex",
    },
    "cmake": {
        "binary": "cmake",
        "mem_limit_mb": 1024,
        "network_required": False,
        "allowed_cidrs": [],
        "level": "recommended",
        "profiles": ["binutils"],
        "required_for": ["cmake-build"],
        "impact": "CMake based projects cannot be configured.",
        "install_hint_id": "cmake",
        "version_args": ["--version"],
        "dnf_package": "cmake",
    },
    "ninja": {
        "binary": "ninja",
        "mem_limit_mb": 1024,
        "network_required": False,
        "allowed_cidrs": [],
        "level": "recommended",
        "profiles": ["binutils"],
        "required_for": ["ninja-build"],
        "impact": "Ninja based builds cannot run.",
        "install_hint_id": "ninja",
        "version_args": ["--version"],
        "dnf_package": "ninja-build",
    },
    "pkg-config": {
        "binary": "pkg-config",
        "mem_limit_mb": 512,
        "network_required": False,
        "allowed_cidrs": [],
        "level": "recommended",
        "profiles": ["binutils"],
        "required_for": ["dependency-discovery"],
        "impact": "Native dependency discovery may fail.",
        "install_hint_id": "pkg-config",
        "version_args": ["--version"],
        "dnf_package": "pkgconf-pkg-config",
    },
    "timeout": {
        "binary": "timeout",
        "mem_limit_mb": 256,
        "network_required": False,
        "allowed_cidrs": [],
        "level": "recommended",
        "profiles": ["binutils"],
        "required_for": ["bounded-validation"],
        "impact": "Validation commands cannot be bounded with timeout.",
        "install_hint_id": "coreutils-timeout",
        "version_args": ["--version"],
        "dnf_package": "coreutils",
    },
}

PROFILE_TOOLS = {
    "minimal": ["rg"],
    "standard": ["rg", "semgrep", "cppcheck", "osv-scanner", "npm"],
    "full": ["rg", "semgrep", "cppcheck", "osv-scanner", "npm", "codeql", "joern", "syft", "grype", "trivy", "afl-fuzz"],
    "binutils": [
        "rg", "semgrep", "cppcheck", "osv-scanner", "codeql",
        "gcc", "g++", "clang", "clang++", "llvm-symbolizer", "llvm-profdata", "llvm-cov",
        "make", "timeout", "autoconf", "automake", "libtool", "bison", "flex",
        "cmake", "ninja", "pkg-config", "afl-fuzz",
    ],
}

# Directories to search for traditional tool binaries when PATH lookup fails.
COMMON_BIN_DIRS: list[str] = [
    "/usr/bin",
    "/usr/local/bin",
    "~/.local/bin",
    "~/.pvas/bin",
]

STRICT_REQUIRED_TOOLS = {
    "minimal": ["rg"],
    "standard": ["rg", "semgrep", "cppcheck", "osv-scanner"],
    "binutils": ["rg", "semgrep", "cppcheck", "osv-scanner", "gcc", "g++", "clang", "clang++", "llvm-symbolizer", "make", "timeout"],
    "full": ["rg", "semgrep", "cppcheck", "osv-scanner", "codeql", "syft", "grype"],
}

CONTROLLED_INSTALL_METHOD_ORDER = [
    "offline-bundle",
    "python-pipx",
    "python-uv",
    "npm-npx",
    "github-release-download",
    "user-local-binary",
    "user-local-distribution",
    "go-install-user-local",
    "admin-rpm-dnf-plan",
]

INSTALL_HINTS = {
    "semgrep": [
        {"priority": 0, "method": "offline-bundle", "commands": ["python3 tools/install_assistant.py --tool semgrep --mode strict --dry-run --offline-bundle offline-bundle"], "notes": "Preferred controlled path: verify offline-bundle manifest/hash and install into an approved user prefix only after per-tool authorization."},
        {"priority": 1, "method": "python-pipx", "commands": ["python3 -m pip install --user pipx", "python3 -m pipx ensurepath", "pipx install semgrep"], "notes": "User-local isolated Python CLI install. Requires explicit per-tool authorization and allowed network or internal index."},
        {"priority": 2, "method": "python-uv", "commands": ["uv tool install semgrep"], "notes": "Alternative isolated Python tool installer. Requires explicit per-tool authorization and allowed network or internal index."},
        {"priority": 9, "method": "admin-rpm-dnf-plan", "commands": ["# Last-resort administrator plan only; do not execute automatically", "# sudo dnf install <approved-semgrep-package-or-local-rpm>"], "notes": "System package management requires separate system-install authorization and is never executed by default."},
    ],
    "cppcheck": [
        {"priority": 0, "method": "offline-bundle", "commands": ["python3 tools/install_assistant.py --tool cppcheck --mode strict --dry-run --offline-bundle offline-bundle"], "notes": "Preferred controlled path: offline binary/RPM payload verified by hash and installed into the user prefix only after authorization."},
        {"priority": 4, "method": "user-local-binary", "commands": ["mkdir -p ~/.pvas/bin", "install -m 0755 cppcheck ~/.pvas/bin/cppcheck", "export PATH=\"$HOME/.pvas/bin:$PATH\""], "notes": "Use a vetted user-local binary from the offline bundle or internal artifact store."},
        {"priority": 9, "method": "admin-rpm-dnf-plan", "commands": ["# Last-resort administrator plan only", "# sudo dnf install cppcheck"], "notes": "RPM/DNF is a final administrator option; do not execute without separate authorization."},
    ],
    "osv-scanner": [
        {"priority": 0, "method": "offline-bundle", "commands": ["python3 tools/install_assistant.py --tool osv-scanner --mode strict --dry-run --offline-bundle offline-bundle"], "notes": "Preferred controlled path: verified offline-bundle binary installed under the user prefix."},
        {"priority": 3, "method": "github-release-download", "commands": ["install_assistant.py --tool osv-scanner --network-mode online-approved --execute"], "notes": "Download the official prebuilt Linux binary from GitHub releases (github.com/google/osv-scanner). Requires --network-mode online-approved and explicit --authorize-tool osv-scanner. Architecture auto-detected."},
        {"priority": 4, "method": "user-local-binary", "commands": ["mkdir -p ~/.pvas/bin", "install -m 0755 osv-scanner ~/.pvas/bin/osv-scanner", "export PATH=\"$HOME/.pvas/bin:$PATH\""], "notes": "Use the official/pre-approved prebuilt binary or an internal mirror."},
        {"priority": 5, "method": "go-install-user-local", "commands": ["GOBIN=$HOME/.pvas/bin go install github.com/google/osv-scanner/v2/cmd/osv-scanner@latest"], "notes": "Requires Go plus an approved network/proxy mode; not used in offline mode."},
        {"priority": 9, "method": "admin-rpm-dnf-plan", "commands": ["# Last-resort administrator plan only", "# sudo dnf install <approved-osv-scanner-package-or-local-rpm>"], "notes": "System package management requires separate authorization."},
    ],
    "npm": [
        {"priority": 0, "method": "offline-bundle", "commands": ["# Use an approved Node.js/npm offline bundle and validate bundle hashes first"], "notes": "Preferred for controlled networks. npx remote fetch is disabled unless network mode authorizes it."},
        {"priority": 3, "method": "npm-npx", "commands": ["npm --version", "npm audit --json"], "notes": "Only run against local project dependencies or approved registries; npx remote package execution needs explicit network authorization."},
        {"priority": 9, "method": "admin-rpm-dnf-plan", "commands": ["# Last-resort administrator plan only", "# sudo dnf install nodejs npm"], "notes": "Do not execute system package manager by default."},
    ],
    "codeql": [
        {"priority": 0, "method": "offline-bundle", "commands": ["python3 tools/install_assistant.py --tool codeql --mode strict --dry-run --offline-bundle offline-bundle"], "notes": "Preferred controlled path: verified CodeQL bundle extracted into the user prefix."},
        {"priority": 4, "method": "user-local-distribution", "commands": ["mkdir -p ~/.pvas/codeql", "# Extract approved CodeQL bundle into ~/.pvas/codeql", "export PATH=\"$HOME/.pvas/codeql:$PATH\"", "codeql version"], "notes": "Use official CodeQL CLI bundle or internal mirror; glibc Linux required."},
    ],
    "syft": [
        {"priority": 0, "method": "offline-bundle", "commands": ["python3 tools/install_assistant.py --tool syft --mode strict --dry-run --offline-bundle offline-bundle"], "notes": "Preferred controlled path: verified offline-bundle binary."},
        {"priority": 4, "method": "user-local-binary", "commands": ["mkdir -p ~/.pvas/bin", "install -m 0755 syft ~/.pvas/bin/syft"], "notes": "Use approved user-local binary."},
    ],
    "grype": [
        {"priority": 0, "method": "offline-bundle", "commands": ["python3 tools/install_assistant.py --tool grype --mode strict --dry-run --offline-bundle offline-bundle"], "notes": "Preferred controlled path: verified offline-bundle binary."},
        {"priority": 4, "method": "user-local-binary", "commands": ["mkdir -p ~/.pvas/bin", "install -m 0755 grype ~/.pvas/bin/grype"], "notes": "Use approved user-local binary."},
    ],
    "trivy": [
        {"priority": 0, "method": "offline-bundle", "commands": ["python3 tools/install_assistant.py --tool trivy --mode strict --dry-run --offline-bundle offline-bundle"], "notes": "Preferred controlled path: verified offline-bundle binary."},
        {"priority": 4, "method": "user-local-binary", "commands": ["mkdir -p ~/.pvas/bin", "install -m 0755 trivy ~/.pvas/bin/trivy"], "notes": "Use approved user-local binary."},
    ],
    "rg": [
        {"priority": 0, "method": "offline-bundle", "commands": ["python3 tools/install_assistant.py --tool rg --mode strict --dry-run --offline-bundle offline-bundle"], "notes": "Preferred controlled path: verified ripgrep binary from offline bundle."},
        {"priority": 4, "method": "user-local-binary", "commands": ["mkdir -p ~/.pvas/bin", "install -m 0755 rg ~/.pvas/bin/rg"], "notes": "Use approved user-local binary."},
        {"priority": 9, "method": "admin-rpm-dnf-plan", "commands": ["# Last-resort administrator plan only", "# sudo dnf install ripgrep"], "notes": "Do not execute RPM/DNF without separate system-install authorization."},
    ],
    "joern": [
        {"priority": 0, "method": "offline-bundle", "commands": ["# Extract approved Joern offline distribution after hash validation"], "notes": "Preferred controlled path."},
        {"priority": 4, "method": "user-local-distribution", "commands": ["# Extract Joern distribution into ~/.pvas/joern", "export PATH=\"$HOME/.pvas/joern:$PATH\""], "notes": "Prefer internal mirrored distribution for offline environments."},
    ],
    "afl-fuzz": [
        {"priority": 0, "method": "offline-bundle", "commands": ["# Use an approved AFL++ container/image/build artifact; keep fuzzing separate from baseline scan"], "notes": "Fuzzing is not a default strict-mode gate unless explicitly required."},
        {"priority": 4, "method": "user-local-binary", "commands": ["# Install approved afl-fuzz binary/build under ~/.pvas"], "notes": "Do not install system-wide by default."},
    ],
    "gcc": [
        {"priority": 0, "method": "offline-bundle", "commands": ["# Use approved offline toolchain bundle or existing build environment"], "notes": "Compiler toolchains are environment dependencies; do not mutate system by default."},
        {"priority": 9, "method": "admin-rpm-dnf-plan", "commands": ["# Last-resort administrator plan only", "# sudo dnf install gcc"], "notes": "Requires separate system-install authorization."},
    ],
    "g++": [
        {"priority": 0, "method": "offline-bundle", "commands": ["# Use approved offline C++ toolchain bundle or existing build environment"], "notes": "Compiler toolchains are environment dependencies; do not mutate system by default."},
        {"priority": 9, "method": "admin-rpm-dnf-plan", "commands": ["# Last-resort administrator plan only", "# sudo dnf install gcc-c++"], "notes": "Requires separate system-install authorization."},
    ],
    "clang": [
        {"priority": 0, "method": "offline-bundle", "commands": ["# Use approved offline LLVM/Clang bundle or existing runtime image package"], "notes": "Preferred for controlled networks and container image rebuilds."},
        {"priority": 9, "method": "admin-rpm-dnf-plan", "commands": ["# Last-resort administrator plan only", "# sudo dnf install clang llvm compiler-rt"], "notes": "Requires separate system-install authorization."},
    ],
    "clang++": [
        {"priority": 0, "method": "offline-bundle", "commands": ["# Use approved offline LLVM/Clang bundle or existing runtime image package"], "notes": "Preferred for controlled networks and container image rebuilds."},
        {"priority": 9, "method": "admin-rpm-dnf-plan", "commands": ["# Last-resort administrator plan only", "# sudo dnf install clang llvm compiler-rt"], "notes": "Requires separate system-install authorization."},
    ],
    "llvm-symbolizer": [
        {"priority": 0, "method": "offline-bundle", "commands": ["# Use approved offline LLVM bundle or existing runtime image package"], "notes": "Required for sanitizer symbolization in validation."},
        {"priority": 9, "method": "admin-rpm-dnf-plan", "commands": ["# Last-resort administrator plan only", "# sudo dnf install llvm"], "notes": "Requires separate system-install authorization."},
    ],
    "llvm-profdata": [
        {"priority": 0, "method": "offline-bundle", "commands": ["# Use approved offline LLVM bundle or existing runtime image package"], "notes": "Optional coverage tooling."},
        {"priority": 9, "method": "admin-rpm-dnf-plan", "commands": ["# Last-resort administrator plan only", "# sudo dnf install llvm"], "notes": "Requires separate system-install authorization."},
    ],
    "llvm-cov": [
        {"priority": 0, "method": "offline-bundle", "commands": ["# Use approved offline LLVM bundle or existing runtime image package"], "notes": "Optional coverage tooling."},
        {"priority": 9, "method": "admin-rpm-dnf-plan", "commands": ["# Last-resort administrator plan only", "# sudo dnf install llvm"], "notes": "Requires separate system-install authorization."},
    ],
    "make": [
        {"priority": 0, "method": "offline-bundle", "commands": ["# Use approved offline build tools bundle or existing build environment"], "notes": "Build tools are environment dependencies; do not mutate system by default."},
        {"priority": 9, "method": "admin-rpm-dnf-plan", "commands": ["# Last-resort administrator plan only", "# sudo dnf install make"], "notes": "Requires separate system-install authorization."},
    ],
    "coreutils-timeout": [
        {"priority": 0, "method": "offline-bundle", "commands": ["# Use approved coreutils/timeout from existing environment or offline bundle"], "notes": "Usually provided by GNU coreutils."},
        {"priority": 9, "method": "admin-rpm-dnf-plan", "commands": ["# Last-resort administrator plan only", "# sudo dnf install coreutils"], "notes": "Requires separate system-install authorization."},
    ],
}

for _name in ("autoconf", "automake", "libtool", "bison", "flex", "cmake", "ninja", "pkg-config"):
    INSTALL_HINTS.setdefault(_name, [
        {"priority": 0, "method": "offline-bundle", "commands": [f"# Use approved offline {_name} bundle or rebuild the runtime image with dnf"], "notes": "Container runtime dependency; do not mutate the host by default."},
        {"priority": 9, "method": "admin-rpm-dnf-plan", "commands": [f"# Last-resort administrator plan only", f"# sudo dnf install {CATALOG[_name]['dnf_package']}"], "notes": "Requires separate system-install authorization."},
    ])


def _install_methods_for(name: str, meta: dict) -> list[str]:
    methods = [item["method"] for item in INSTALL_HINTS.get(meta.get("install_hint_id", name), INSTALL_HINTS.get(name, []))]
    if meta.get("dnf_package") and "admin-rpm-dnf-plan" not in methods:
        methods.append("admin-rpm-dnf-plan")
    return methods or ["offline-bundle"]


for _name, _meta in CATALOG.items():
    _meta.setdefault("runtime_scope", "container-optional" if _meta.get("level") == "optional" else "container-required")
    if _name in {"clang", "clang++", "llvm-symbolizer", "gcc", "g++", "make", "timeout"}:
        _meta["runtime_scope"] = "validation-required"
    _meta.setdefault("install_methods", _install_methods_for(_name, _meta))
